resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

stages:
- stage: dynamic
  jobs:
    - template: third-party-library-all-platforms-from-local-recipe.yml@templates
      parameters:
        package: lexfloatclient
        package_version: 4.5.2
        destination_repository: ccdc-3rdparty-conan
        # Once without to build the dynamic version
        # additional_profiles_for_all_platforms: static-cryptlex

- stage: static
  jobs:
    - template: third-party-library-all-platforms-from-local-recipe.yml@templates
      parameters:
        package: lexfloatclient
        package_version: 4.5.2
        destination_repository: ccdc-3rdparty-conan
        # Once with to build the static version
        additional_profiles_for_all_platforms: static-cryptlex
